Method,Name,Error,Occurrences
GET,/Categorias,"ConnectionResetError(10054, 'Se ha forzado la interrupción de una conexión existente por el host remoto', None, 10054, None)",6
PUT,Abrir Mesa,CatchResponseError('Fallo al abrir mesa 7'),441
PUT,Cerrar Mesa,CatchResponseError('Fallo al cerrar mesa 6'),604
GET,/Productos,"ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x....>, 'Connection to 192.168.100.15 timed out. (connect timeout=None)')",1
POST,Agregar Item,CatchResponseError('Fallo al agregar item 1 en mesa 3'),458
PUT,Cerrar Mesa,CatchResponseError('Fallo al cerrar mesa 8'),622
POST,Agregar Item,CatchResponseError('Fallo al agregar item 3 en mesa 2'),411
POST,Agregar Item,CatchResponseError('Fallo al agregar item 3 en mesa 3'),464
GET,/Categorias,"ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x....>, 'Connection to 192.168.100.15 timed out. (connect timeout=None)')",32
POST,Agregar Item,CatchResponseError('Fallo al agregar item 1 en mesa 4'),445
POST,Agregar Item,CatchResponseError('Fallo al agregar item 4 en mesa 7'),448
PUT,Abrir Mesa,CatchResponseError('Fallo al abrir mesa 1'),442
POST,Agregar Item,CatchResponseError('Fallo al agregar item 4 en mesa 4'),478
GET,/Pedidos/5925,HTTPError('500 Server Error: Internal Server Error for url: /Pedidos/5925'),3
POST,Agregar Item,CatchResponseError('Fallo al agregar item 4 en mesa 12'),463
PUT,Abrir Mesa,CatchResponseError('Fallo al abrir mesa 11'),440
GET,/Mesas,RemoteDisconnected('Remote end closed connection without response'),706
POST,Agregar Item,CatchResponseError('Fallo al agregar item 2 en mesa 9'),456
PUT,Abrir Mesa,CatchResponseError('Fallo al abrir mesa 3'),449
POST,Agregar Item,CatchResponseError('Fallo al agregar item 3 en mesa 7'),495
PUT,Cerrar Mesa,CatchResponseError('Fallo al cerrar mesa 9'),621
GET,/Productos,"ConnectionResetError(10054, 'Se ha forzado la interrupción de una conexión existente por el host remoto', None, 10054, None)",2
POST,Agregar Item,CatchResponseError('Fallo al agregar item 3 en mesa 9'),463
GET,/Pedidos/5925,RemoteDisconnected('Remote end closed connection without response'),2326
POST,Agregar Item,CatchResponseError('Fallo al agregar item 2 en mesa 12'),428
PUT,Cerrar Mesa,CatchResponseError('Fallo al cerrar mesa 2'),655
GET,/Mesas,"ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x....>, 'Connection to 192.168.100.15 timed out. (connect timeout=None)')",7
POST,Agregar Item,CatchResponseError('Fallo al agregar item 1 en mesa 11'),506
POST,Agregar Item,CatchResponseError('Fallo al agregar item 2 en mesa 3'),419
GET,/Pedidos/5925,"ConnectionResetError(10054, 'Se ha forzado la interrupción de una conexión existente por el host remoto', None, 10054, None)",4
POST,Agregar Item,CatchResponseError('Fallo al agregar item 4 en mesa 9'),448
GET,/Categorias,HTTPError('500 Server Error: Internal Server Error for url: /Categorias'),5
PUT,Cerrar Mesa,CatchResponseError('Fallo al cerrar mesa 7'),613
POST,Agregar Item,CatchResponseError('Fallo al agregar item 3 en mesa 1'),441
PUT,Cerrar Mesa,CatchResponseError('Fallo al cerrar mesa 10'),640
POST,Agregar Item,CatchResponseError('Fallo al agregar item 3 en mesa 13'),436
GET,/Mesas,HTTPError('500 Server Error: Internal Server Error for url: /Mesas'),1
POST,Agregar Item,CatchResponseError('Fallo al agregar item 1 en mesa 8'),451
GET,/Pedidos/5925,"ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x....>, 'Connection to 192.168.100.15 timed out. (connect timeout=None)')",35
POST,Agregar Item,CatchResponseError('Fallo al agregar item 1 en mesa 1'),449
POST,Agregar Item,CatchResponseError('Fallo al agregar item 3 en mesa 12'),455
GET,/Categorias,RemoteDisconnected('Remote end closed connection without response'),3023
POST,Agregar Item,CatchResponseError('Fallo al agregar item 4 en mesa 2'),483
POST,Agregar Item,CatchResponseError('Fallo al agregar item 4 en mesa 13'),445
PUT,Abrir Mesa,CatchResponseError('Fallo al abrir mesa 5'),418
PUT,Abrir Mesa,CatchResponseError('Fallo al abrir mesa 8'),452
POST,Agregar Item,CatchResponseError('Fallo al agregar item 1 en mesa 5'),406
POST,Agregar Item,CatchResponseError('Fallo al agregar item 2 en mesa 5'),415
POST,Agregar Item,CatchResponseError('Fallo al agregar item 4 en mesa 1'),467
POST,Agregar Item,CatchResponseError('Fallo al agregar item 1 en mesa 12'),474
POST,Agregar Item,CatchResponseError('Fallo al agregar item 1 en mesa 9'),449
PUT,Abrir Mesa,CatchResponseError('Fallo al abrir mesa 10'),445
PUT,Cerrar Mesa,CatchResponseError('Fallo al cerrar mesa 1'),623
PUT,Abrir Mesa,CatchResponseError('Fallo al abrir mesa 2'),440
POST,Agregar Item,CatchResponseError('Fallo al agregar item 2 en mesa 8'),453
PUT,Cerrar Mesa,CatchResponseError('Fallo al cerrar mesa 4'),674
POST,Agregar Item,CatchResponseError('Fallo al agregar item 3 en mesa 11'),407
POST,Agregar Item,CatchResponseError('Fallo al agregar item 1 en mesa 2'),465
POST,Agregar Item,CatchResponseError('Fallo al agregar item 1 en mesa 7'),487
PUT,Cerrar Mesa,CatchResponseError('Fallo al cerrar mesa 3'),593
PUT,Cerrar Mesa,CatchResponseError('Fallo al cerrar mesa 5'),597
POST,Agregar Item,CatchResponseError('Fallo al agregar item 2 en mesa 13'),444
PUT,Abrir Mesa,CatchResponseError('Fallo al abrir mesa 6'),470
PUT,Abrir Mesa,CatchResponseError('Fallo al abrir mesa 9'),477
PUT,Abrir Mesa,CatchResponseError('Fallo al abrir mesa 4'),457
POST,Agregar Item,CatchResponseError('Fallo al agregar item 2 en mesa 11'),445
GET,/Productos,RemoteDisconnected('Remote end closed connection without response'),6114
POST,Agregar Item,CatchResponseError('Fallo al agregar item 4 en mesa 11'),460
POST,Agregar Item,CatchResponseError('Fallo al agregar item 1 en mesa 13'),444
POST,Agregar Item,CatchResponseError('Fallo al agregar item 3 en mesa 4'),450
POST,Agregar Item,CatchResponseError('Fallo al agregar item 2 en mesa 2'),431
POST,Agregar Item,CatchResponseError('Fallo al agregar item 4 en mesa 5'),409
POST,Agregar Item,CatchResponseError('Fallo al agregar item 4 en mesa 8'),420
POST,Agregar Item,CatchResponseError('Fallo al agregar item 2 en mesa 1'),470
POST,Agregar Item,CatchResponseError('Fallo al agregar item 3 en mesa 5'),435
POST,Agregar Item,CatchResponseError('Fallo al agregar item 3 en mesa 8'),443
POST,Agregar Item,CatchResponseError('Fallo al agregar item 2 en mesa 4'),404
PUT,Cerrar Mesa,CatchResponseError('Fallo al cerrar mesa 11'),651
POST,Agregar Item,CatchResponseError('Fallo al agregar item 4 en mesa 3'),501
POST,Agregar Item,CatchResponseError('Fallo al agregar item 2 en mesa 7'),523
