Method,Name,Error,Occurrences
GET,/Categorias,"ConnectionResetError(10054, 'Se ha forzado la interrupción de una conexión existente por el host remoto', None, 10054, None)",1
PUT,Abrir Mesa,CatchResponseError('Fallo al abrir mesa 7'),249
PUT,Cerrar Mesa,CatchResponseError('Fallo al cerrar mesa 6'),325
GET,/Productos,"ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x....>, 'Connection to 192.168.100.15 timed out. (connect timeout=None)')",6
POST,Agregar Item,CatchResponseError('Fallo al agregar item 1 en mesa 3'),265
PUT,Cerrar Mesa,CatchResponseError('Fallo al cerrar mesa 8'),327
GET,/Categorias,"ConnectionAbortedError(10053, 'Se ha anulado una conexión establecida por el software en su equipo host', None, 10053, None)",60
POST,Agregar Item,CatchResponseError('Fallo al agregar item 3 en mesa 2'),247
POST,Agregar Item,CatchResponseError('Fallo al agregar item 3 en mesa 3'),229
GET,/Categorias,"ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x....>, 'Connection to 192.168.100.15 timed out. (connect timeout=None)')",38
POST,Agregar Item,CatchResponseError('Fallo al agregar item 1 en mesa 4'),292
POST,Agregar Item,CatchResponseError('Fallo al agregar item 4 en mesa 7'),241
PUT,Abrir Mesa,CatchResponseError('Fallo al abrir mesa 1'),290
POST,Agregar Item,CatchResponseError('Fallo al agregar item 4 en mesa 4'),248
GET,/Pedidos/5925,HTTPError('500 Server Error: Internal Server Error for url: /Pedidos/5925'),4
POST,Agregar Item,CatchResponseError('Fallo al agregar item 4 en mesa 12'),275
PUT,Abrir Mesa,CatchResponseError('Fallo al abrir mesa 11'),252
GET,/Mesas,RemoteDisconnected('Remote end closed connection without response'),1243
POST,Agregar Item,CatchResponseError('Fallo al agregar item 2 en mesa 9'),270
PUT,Abrir Mesa,CatchResponseError('Fallo al abrir mesa 3'),276
POST,Agregar Item,CatchResponseError('Fallo al agregar item 3 en mesa 7'),243
PUT,Cerrar Mesa,CatchResponseError('Fallo al cerrar mesa 9'),398
POST,Agregar Item,CatchResponseError('Fallo al agregar item 3 en mesa 9'),251
GET,/Pedidos/5925,RemoteDisconnected('Remote end closed connection without response'),3936
POST,Agregar Item,CatchResponseError('Fallo al agregar item 2 en mesa 12'),265
PUT,Cerrar Mesa,CatchResponseError('Fallo al cerrar mesa 2'),325
GET,/Mesas,"ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x....>, 'Connection to 192.168.100.15 timed out. (connect timeout=None)')",12
POST,Agregar Item,CatchResponseError('Fallo al agregar item 1 en mesa 11'),235
POST,Agregar Item,CatchResponseError('Fallo al agregar item 2 en mesa 3'),265
GET,/Pedidos/5925,"ConnectionResetError(10054, 'Se ha forzado la interrupción de una conexión existente por el host remoto', None, 10054, None)",2
POST,Agregar Item,CatchResponseError('Fallo al agregar item 4 en mesa 9'),262
GET,/Categorias,HTTPError('500 Server Error: Internal Server Error for url: /Categorias'),4
GET,/Mesas,"ConnectionAbortedError(10053, 'Se ha anulado una conexión establecida por el software en su equipo host', None, 10053, None)",13
PUT,Cerrar Mesa,CatchResponseError('Fallo al cerrar mesa 7'),308
POST,Agregar Item,CatchResponseError('Fallo al agregar item 3 en mesa 1'),272
PUT,Cerrar Mesa,CatchResponseError('Fallo al cerrar mesa 10'),355
POST,Agregar Item,CatchResponseError('Fallo al agregar item 3 en mesa 13'),277
GET,/Mesas,HTTPError('500 Server Error: Internal Server Error for url: /Mesas'),1
POST,Agregar Item,CatchResponseError('Fallo al agregar item 1 en mesa 8'),285
GET,/Pedidos/5925,"ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x....>, 'Connection to 192.168.100.15 timed out. (connect timeout=None)')",31
POST,Agregar Item,CatchResponseError('Fallo al agregar item 1 en mesa 1'),290
POST,Agregar Item,CatchResponseError('Fallo al agregar item 3 en mesa 12'),271
GET,/Categorias,RemoteDisconnected('Remote end closed connection without response'),5293
POST,Agregar Item,CatchResponseError('Fallo al agregar item 4 en mesa 2'),261
POST,Agregar Item,CatchResponseError('Fallo al agregar item 4 en mesa 13'),262
GET,/Mesas,"ConnectionResetError(10054, 'Se ha forzado la interrupción de una conexión existente por el host remoto', None, 10054, None)",2
PUT,Abrir Mesa,CatchResponseError('Fallo al abrir mesa 5'),294
PUT,Abrir Mesa,CatchResponseError('Fallo al abrir mesa 8'),236
POST,Agregar Item,CatchResponseError('Fallo al agregar item 1 en mesa 5'),240
POST,Agregar Item,CatchResponseError('Fallo al agregar item 2 en mesa 5'),226
POST,Agregar Item,CatchResponseError('Fallo al agregar item 4 en mesa 1'),244
POST,Agregar Item,CatchResponseError('Fallo al agregar item 1 en mesa 12'),280
POST,Agregar Item,CatchResponseError('Fallo al agregar item 1 en mesa 9'),263
GET,/Productos,"ConnectionAbortedError(10053, 'Se ha anulado una conexión establecida por el software en su equipo host', None, 10053, None)",45
PUT,Abrir Mesa,CatchResponseError('Fallo al abrir mesa 10'),252
PUT,Cerrar Mesa,CatchResponseError('Fallo al cerrar mesa 1'),379
PUT,Abrir Mesa,CatchResponseError('Fallo al abrir mesa 2'),254
POST,Agregar Item,CatchResponseError('Fallo al agregar item 2 en mesa 8'),272
PUT,Cerrar Mesa,CatchResponseError('Fallo al cerrar mesa 4'),329
POST,Agregar Item,CatchResponseError('Fallo al agregar item 3 en mesa 11'),252
POST,Agregar Item,CatchResponseError('Fallo al agregar item 1 en mesa 2'),260
POST,Agregar Item,CatchResponseError('Fallo al agregar item 1 en mesa 7'),310
PUT,Cerrar Mesa,CatchResponseError('Fallo al cerrar mesa 3'),367
PUT,Cerrar Mesa,CatchResponseError('Fallo al cerrar mesa 5'),413
POST,Agregar Item,CatchResponseError('Fallo al agregar item 2 en mesa 13'),280
PUT,Abrir Mesa,CatchResponseError('Fallo al abrir mesa 6'),251
GET,/Pedidos/5925,"ConnectionAbortedError(10053, 'Se ha anulado una conexión establecida por el software en su equipo host', None, 10053, None)",53
PUT,Abrir Mesa,CatchResponseError('Fallo al abrir mesa 9'),261
PUT,Abrir Mesa,CatchResponseError('Fallo al abrir mesa 4'),241
POST,Agregar Item,CatchResponseError('Fallo al agregar item 2 en mesa 11'),271
GET,/Productos,RemoteDisconnected('Remote end closed connection without response'),2679
POST,Agregar Item,CatchResponseError('Fallo al agregar item 4 en mesa 11'),273
POST,Agregar Item,CatchResponseError('Fallo al agregar item 1 en mesa 13'),266
POST,Agregar Item,CatchResponseError('Fallo al agregar item 3 en mesa 4'),260
POST,Agregar Item,CatchResponseError('Fallo al agregar item 2 en mesa 2'),257
POST,Agregar Item,CatchResponseError('Fallo al agregar item 4 en mesa 5'),255
POST,Agregar Item,CatchResponseError('Fallo al agregar item 4 en mesa 8'),278
POST,Agregar Item,CatchResponseError('Fallo al agregar item 2 en mesa 1'),275
POST,Agregar Item,CatchResponseError('Fallo al agregar item 3 en mesa 5'),246
POST,Agregar Item,CatchResponseError('Fallo al agregar item 3 en mesa 8'),283
POST,Agregar Item,CatchResponseError('Fallo al agregar item 2 en mesa 4'),243
PUT,Cerrar Mesa,CatchResponseError('Fallo al cerrar mesa 11'),357
POST,Agregar Item,CatchResponseError('Fallo al agregar item 4 en mesa 3'),244
POST,Agregar Item,CatchResponseError('Fallo al agregar item 2 en mesa 7'),248
