Method,Name,Error,Occurrences
GET,/Categorias,"ConnectionResetError(10054, 'Se ha forzado la interrupción de una conexión existente por el host remoto', None, 10054, None)",460
PUT,Abrir Mesa,CatchResponseError('Fallo al abrir mesa 7'),638
PUT,Cerrar Mesa,CatchResponseError('Fallo al cerrar mesa 6'),256
GET,/Productos,"ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x....>, 'Connection to 192.168.100.15 timed out. (connect timeout=None)')",254
POST,Agregar Item,CatchResponseError('Fallo al agregar item 1 en mesa 3'),184
PUT,Cerrar Mesa,CatchResponseError('Fallo al cerrar mesa 8'),277
POST,Agregar Item,CatchResponseError('Fallo al agregar item 3 en mesa 2'),188
POST,Agregar Item,CatchResponseError('Fallo al agregar item 3 en mesa 3'),197
GET,/Categorias,"ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x....>, 'Connection to 192.168.100.15 timed out. (connect timeout=None)')",578
POST,Agregar Item,CatchResponseError('Fallo al agregar item 1 en mesa 4'),194
POST,Agregar Item,CatchResponseError('Fallo al agregar item 4 en mesa 7'),175
PUT,Abrir Mesa,CatchResponseError('Fallo al abrir mesa 1'),644
POST,Agregar Item,CatchResponseError('Fallo al agregar item 4 en mesa 4'),212
GET,/Pedidos/5925,HTTPError('500 Server Error: Internal Server Error for url: /Pedidos/5925'),2444
POST,Agregar Item,CatchResponseError('Fallo al agregar item 4 en mesa 12'),176
PUT,Abrir Mesa,CatchResponseError('Fallo al abrir mesa 11'),608
GET,/Mesas,RemoteDisconnected('Remote end closed connection without response'),189
POST,Agregar Item,CatchResponseError('Fallo al agregar item 2 en mesa 9'),170
PUT,Abrir Mesa,CatchResponseError('Fallo al abrir mesa 3'),616
POST,Agregar Item,CatchResponseError('Fallo al agregar item 3 en mesa 7'),179
PUT,Cerrar Mesa,CatchResponseError('Fallo al cerrar mesa 9'),248
GET,/Productos,"ConnectionResetError(10054, 'Se ha forzado la interrupción de una conexión existente por el host remoto', None, 10054, None)",204
POST,Agregar Item,CatchResponseError('Fallo al agregar item 3 en mesa 9'),182
GET,/Pedidos/5925,RemoteDisconnected('Remote end closed connection without response'),536
POST,Agregar Item,CatchResponseError('Fallo al agregar item 2 en mesa 12'),222
PUT,Cerrar Mesa,CatchResponseError('Fallo al cerrar mesa 2'),256
GET,/Mesas,"ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x....>, 'Connection to 192.168.100.15 timed out. (connect timeout=None)')",173
POST,Agregar Item,CatchResponseError('Fallo al agregar item 1 en mesa 11'),170
POST,Agregar Item,CatchResponseError('Fallo al agregar item 2 en mesa 3'),162
GET,/Pedidos/5925,"ConnectionResetError(10054, 'Se ha forzado la interrupción de una conexión existente por el host remoto', None, 10054, None)",323
POST,Agregar Item,CatchResponseError('Fallo al agregar item 4 en mesa 9'),181
GET,/Categorias,HTTPError('500 Server Error: Internal Server Error for url: /Categorias'),3073
PUT,Cerrar Mesa,CatchResponseError('Fallo al cerrar mesa 7'),249
POST,Agregar Item,CatchResponseError('Fallo al agregar item 3 en mesa 1'),153
PUT,Cerrar Mesa,CatchResponseError('Fallo al cerrar mesa 10'),256
POST,Agregar Item,CatchResponseError('Fallo al agregar item 3 en mesa 13'),172
GET,/Mesas,HTTPError('500 Server Error: Internal Server Error for url: /Mesas'),821
POST,Agregar Item,CatchResponseError('Fallo al agregar item 1 en mesa 8'),181
GET,/Pedidos/5925,"ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x....>, 'Connection to 192.168.100.15 timed out. (connect timeout=None)')",437
POST,Agregar Item,CatchResponseError('Fallo al agregar item 1 en mesa 1'),177
POST,Agregar Item,CatchResponseError('Fallo al agregar item 3 en mesa 12'),158
GET,/Categorias,RemoteDisconnected('Remote end closed connection without response'),693
POST,Agregar Item,CatchResponseError('Fallo al agregar item 4 en mesa 2'),176
POST,Agregar Item,CatchResponseError('Fallo al agregar item 4 en mesa 13'),175
GET,/Mesas,"ConnectionResetError(10054, 'Se ha forzado la interrupción de una conexión existente por el host remoto', None, 10054, None)",102
PUT,Abrir Mesa,CatchResponseError('Fallo al abrir mesa 5'),596
PUT,Abrir Mesa,CatchResponseError('Fallo al abrir mesa 8'),592
POST,Agregar Item,CatchResponseError('Fallo al agregar item 1 en mesa 5'),141
POST,Agregar Item,CatchResponseError('Fallo al agregar item 2 en mesa 5'),152
POST,Agregar Item,CatchResponseError('Fallo al agregar item 4 en mesa 1'),179
POST,Agregar Item,CatchResponseError('Fallo al agregar item 1 en mesa 12'),163
POST,Agregar Item,CatchResponseError('Fallo al agregar item 1 en mesa 9'),176
PUT,Abrir Mesa,CatchResponseError('Fallo al abrir mesa 10'),637
PUT,Cerrar Mesa,CatchResponseError('Fallo al cerrar mesa 1'),253
PUT,Abrir Mesa,CatchResponseError('Fallo al abrir mesa 2'),643
POST,Agregar Item,CatchResponseError('Fallo al agregar item 2 en mesa 8'),190
PUT,Cerrar Mesa,CatchResponseError('Fallo al cerrar mesa 4'),263
POST,Agregar Item,CatchResponseError('Fallo al agregar item 3 en mesa 11'),185
POST,Agregar Item,CatchResponseError('Fallo al agregar item 1 en mesa 2'),189
POST,Agregar Item,CatchResponseError('Fallo al agregar item 1 en mesa 7'),157
PUT,Cerrar Mesa,CatchResponseError('Fallo al cerrar mesa 3'),266
GET,/Productos,HTTPError('500 Server Error: Internal Server Error for url: /Productos'),2957
PUT,Cerrar Mesa,CatchResponseError('Fallo al cerrar mesa 5'),259
POST,Agregar Item,CatchResponseError('Fallo al agregar item 2 en mesa 13'),152
PUT,Abrir Mesa,CatchResponseError('Fallo al abrir mesa 6'),622
PUT,Abrir Mesa,CatchResponseError('Fallo al abrir mesa 9'),646
PUT,Abrir Mesa,CatchResponseError('Fallo al abrir mesa 4'),648
POST,Agregar Item,CatchResponseError('Fallo al agregar item 2 en mesa 11'),171
GET,/Productos,RemoteDisconnected('Remote end closed connection without response'),1583
POST,Agregar Item,CatchResponseError('Fallo al agregar item 4 en mesa 11'),172
POST,Agregar Item,CatchResponseError('Fallo al agregar item 1 en mesa 13'),150
POST,Agregar Item,CatchResponseError('Fallo al agregar item 3 en mesa 4'),172
POST,Agregar Item,CatchResponseError('Fallo al agregar item 2 en mesa 2'),196
POST,Agregar Item,CatchResponseError('Fallo al agregar item 4 en mesa 5'),199
POST,Agregar Item,CatchResponseError('Fallo al agregar item 4 en mesa 8'),174
POST,Agregar Item,CatchResponseError('Fallo al agregar item 2 en mesa 1'),199
POST,Agregar Item,CatchResponseError('Fallo al agregar item 3 en mesa 5'),163
POST,Agregar Item,CatchResponseError('Fallo al agregar item 3 en mesa 8'),171
POST,Agregar Item,CatchResponseError('Fallo al agregar item 2 en mesa 4'),188
PUT,Cerrar Mesa,CatchResponseError('Fallo al cerrar mesa 11'),260
POST,Agregar Item,CatchResponseError('Fallo al agregar item 4 en mesa 3'),166
POST,Agregar Item,CatchResponseError('Fallo al agregar item 2 en mesa 7'),180
